# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c93aab9489dc6b1e5974f76ee1da42fcab673d6be5bcbb1abcc781de153c15422fc2aa57061f6866393008f7c8d12b1a3ae8f2c1bb84c71b6bb0d02b8e7af13d

test:
  secret_key_base: a47601d6b252e9cfc7aa087c862696baefda37213fc1192f9bbaab93db3471e2a218d6c1cb949116b59ce02afe01b26a4b4bae53bb52c9b326a2c8fd31cf4651

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
